### PR TITLE
Review and some changes proposal

### PR DESCRIPTION
**Pull request by dadoonet**

### CODE REVIEW

**Comment by dadoonet** [comment]
I started working on using the High Level Rest client to see where this goes as I think it would reduce a lot the code needed on Vertx side. But I'm struggling ATM with using codegen with elasticsearch classes which are not and can not be annotated with VertX annotations.

**Comment by jponge** [comment]
Thanks @dadoonet I'll have a look soon!

**Comment by jponge** [comment]
It all looks very good to me @dadoonet but I have a timeout when running `./mvnw verify`:

```
[INFO] --- docker-maven-plugin:0.24.0:build (start-elasticsearch) @ vertx-elasticsearch-client ---
[INFO] Building tar: /Users/jponge/Code/vertx/vertx-elasticsearch-client/target/docker/dadoonet/docker-elasticsearch/0-SNAPSHOT/tmp/docker-build.tar
[INFO] DOCKER> [dadoonet/docker-elasticsearch:0-SNAPSHOT] "elasticsearch-it": Created docker-build.tar in 34 milliseconds
[INFO] DOCKER> [dadoonet/docker-elasticsearch:0-SNAPSHOT] "elasticsearch-it": Built image sha256:d8d34
[INFO]
[INFO] --- docker-maven-plugin:0.24.0:stop (start-elasticsearch) @ vertx-elasticsearch-client ---
[INFO]
[INFO] --- docker-maven-plugin:0.24.0:start (start-elasticsearch) @ vertx-elasticsearch-client ---
[INFO] DOCKER> [dadoonet/docker-elasticsearch:0-SNAPSHOT] "elasticsearch-it": Start container 7f7e4de015e1
[INFO] DOCKER> [dadoonet/docker-elasticsearch:0-SNAPSHOT] "elasticsearch-it": Waiting on url http://localhost:9200/ with method HEAD for status 200..499.
[ERROR] DOCKER> [dadoonet/docker-elasticsearch:0-SNAPSHOT] "elasticsearch-it": Timeout after 60263 ms while waiting on url http://localhost:9200/
[ERROR] DOCKER> Error occurred during container startup, shutting down...
[INFO] DOCKER> [dadoonet/docker-elasticsearch:0-SNAPSHOT] "elasticsearch-it": Stop and removed container 7f7e4de015e1 after 0 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2018-05-03T09:34:10+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.24.0:start (start-elasticsearch) on project vertx-elasticsearch-client: Execution start-elasticsearch of goal io.fabric8:docker-maven-plugin:0.24.0:start failed: Start-Job failed with unexpected exception: [dadoonet/docker-elasticsearch:0-SNAPSHOT] "elasticsearch-it": Timeout after 60263 ms while waiting on url http://localhost:9200/ -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by jponge** [comment]
Note: I'm running Docker Version 18.03.1-ce-mac65 (24312)

**Comment by dadoonet** [comment]
It works well on my end. I think this can happen the very first time you are downloading the Docker image from internet.
Then it should start faster.

**Comment by jponge** [comment]
Back from 🏖 

I still have the timeout on my end.

I checked and the Docker image is fully here:

```
$ docker pull docker.elastic.co/elasticsearch/elasticsearch:6.2.3
6.2.3: Pulling from elasticsearch/elasticsearch
Digest: sha256:de7061f7fa78aa78de4b38287fb1f0a21689b685cf1fb6694195088b5c307880
Status: Image is up to date for docker.elastic.co/elasticsearch/elasticsearch:6.2.3
```

Any idea @dadoonet?

**Comment by dadoonet** [comment]
Weird. Can you increase the timeout value?

**Comment by dadoonet** [comment]
I have an idea. I might have pulled the wrong image locally. Let me check that later this week.

**Comment by jponge** [comment]
​Ok, let's see how it goes.

**Comment by dadoonet** [comment]
@jponge I pushed a new change. Could you check again?

**Comment by jponge** [comment]
It works beautifully now 👍 😄

**Comment by jponge** [comment]
Merging, thanks @dadoonet 

I will continue development soon.

**Pull request merged**
